### PR TITLE
stm32/dma: fix build issues + add a configuration for iotlab-m3/nucleo-l152re/f767zi/f207zg

### PR DESCRIPTION
**Pull request by aabadie**
Tested and works for first UART and SPI. Not tested on second UART (and no idea how to do it :)).

You can test on the great IoT-LAB platform ;), and cherry-pick my commits of course.

### CODE REVIEW

**Comment by aabadie** [comment]
also added configuration for nucleo-f767zi (only UARTs). All tested and works.

**Comment by aabadie** [comment]
and also added configuration for nucleo-l152re. All UARTs but the third one are configured, the SPI is configured. First UART and SPI were tested with success.

**Comment by aabadie** [comment]
And now also added a default configuration for the nucleo-f207zg. The SPIs are not tested but all UARTs are working (DMA is disabled for the first one).

**Comment by aabadie** [comment]
And I'm done now: all STMs with DMA have at least one board already configured:
- F0: nucleo-f091rc
- F1: iotlab-m3
- F2: nucleo-f207zg
- F4: nucleo-f413zg
- F7: nucleo-f767zi
- L0: b-l072z-lrwan1
- L4: b-l475e-iot01a

If you merge this PR, I think https://github.com/RIOT-OS/RIOT/pull/9171 will be mergeable.

**Comment by vincent-d** [comment]
> The SPIs are not tested but all UARTs are working (DMA is disabled for the first one).

Why disabling? The whole point of this is that DMA streams can be shared ;)

**Comment by vincent-d** [comment]
> If you merge this PR, I think RIOT-OS#9171 will be mergeable.

Great! I'll take a quick look and I'll merge.

**Comment by aabadie** [comment]
> Why disabling?

Maybe I missed something but the interrupt function cannot be shared.

**Comment by aabadie** [comment]
Ok, so I tried to have 2 peripherals (UART3 and SPI2) on the same stream (DMA1 stream 3) but that doesn't work: the firmware is only able to send but it looks like it doesn't receive.

**Comment by vincent-d** [comment]
It should. Actually each periph driver (uart or spi in our case) "acquire" the stream before using it. So if an UART transfer is ongoing, the SPI will have to wait until it's finished. The dma periph handle sharing the interrupts.

**Comment by aabadie** [comment]
I could make it work by disabling a whole block of code in the UART driver, [here](https://github.com/RIOT-OS/RIOT/blob/master/cpu/stm32_common/periph/uart.c#L228), I replaced `irq_is_in` by `1` and comment out the `else` block, and it works.

**Comment by vincent-d** [comment]
> I could make it work by disabling a whole block of code in the UART driver, here, I replaced irq_is_in by 1 and comment out the else block, and it works.

Doing this is equivalent to disabling DMA for sending. This is weird, there might be a bug in the DMA code then...
In my board, SPI and UART share DMA streams, and I don't have this kind of issues (it might just be luck though :/ )

**Comment by vincent-d** [comment]
Which app/board did you use to test?

**Comment by aabadie** [comment]
nucleo-f207zg, with any app using the shell (examples/default, tests/periph_uart).

I applied this patch to configure DMA on the stdio UART:
```diff
diff --git a/boards/nucleo-f207zg/include/periph_conf.h b/boards/nucleo-f207zg/include/periph_conf.h
index 0d509b04fd..fe4387fb42 100644
--- a/boards/nucleo-f207zg/include/periph_conf.h
+++ b/boards/nucleo-f207zg/include/periph_conf.h
@@ -41,6 +41,7 @@ static const dma_conf_t dma_config[] = {
     { .stream = 3 },    /* DMA1 Stream 4 - SPI2_TX */
     { .stream = 14 },   /* DMA2 Stream 6 - USART6_TX */
     { .stream = 6 },    /* DMA1 Stream 6 - USART2_TX */
+    { .stream = 3 },    /* DMA1 Stream 3 - USART3_TX */
 };
 
 #define DMA_0_ISR  isr_dma2_stream2
@@ -126,9 +127,8 @@ static const uart_conf_t uart_config[] = {
         .bus        = APB1,
         .irqn       = USART3_IRQn,
 #ifdef MODULE_PERIPH_DMA
-        /* disable DMA on first UART because of conflict with SPI2 */
-        .dma        = DMA_STREAM_UNDEF,
-        .dma_chan   = 0
+        .dma        = 6,
+        .dma_chan   = 4
 #endif
     },
     {
```

**Comment by aabadie** [comment]
I found the problem, he was between the keyboard and the chair :)

**Comment by vincent-d** [comment]
This patch works for me:
```
diff --git a/boards/nucleo-f207zg/include/periph_conf.h b/boards/nucleo-f207zg/include/periph_conf.h
index 0d509b04f..972bbbdf6 100644
--- a/boards/nucleo-f207zg/include/periph_conf.h
+++ b/boards/nucleo-f207zg/include/periph_conf.h
@@ -37,8 +37,8 @@ extern "C" {
 static const dma_conf_t dma_config[] = {
     { .stream = 10 },   /* DMA2 Stream 2 - SPI1_RX */
     { .stream = 11 },   /* DMA2 Stream 3 - SPI1_TX */
-    { .stream = 2 },    /* DMA1 Stream 3 - SPI2_RX */
-    { .stream = 3 },    /* DMA1 Stream 4 - SPI2_TX */
+    { .stream = 3 },    /* DMA1 Stream 3 - USART3_TX / SPI2_RX */
+    { .stream = 4 },    /* DMA1 Stream 4 - SPI2_TX */
     { .stream = 14 },   /* DMA2 Stream 6 - USART6_TX */
     { .stream = 6 },    /* DMA1 Stream 6 - USART2_TX */
 };
@@ -126,9 +126,8 @@ static const uart_conf_t uart_config[] = {
         .bus        = APB1,
         .irqn       = USART3_IRQn,
 #ifdef MODULE_PERIPH_DMA
-        /* disable DMA on first UART because of conflict with SPI2 */
-        .dma        = DMA_STREAM_UNDEF,
-        .dma_chan   = 0
+        .dma        = 2,
+        .dma_chan   = 4
 #endif
     },
     {
```

**Comment by aabadie** [comment]
I'll update the nucleo-l152re for which I made the same mistake.

**Comment by aabadie** [comment]
Tested and Nucleo-l152re shared stream works for both USART3 and SPI1. Please merge !

**Pull request merged**
